<?php
// GitHub Webhook Auto-Deploy
// Copy this file to /var/www/html/deploy.php on your server
// Replace YOUR_SECRET_HERE with the secret generated by: openssl rand -hex 16

$secret   = 'YOUR_SECRET_HERE';
$repoPath = '/var/www/html/iit';
$logFile  = '/var/log/deploy.log';

// Verify GitHub's HMAC-SHA256 signature
$signature = $_SERVER['HTTP_X_HUB_SIGNATURE_256'] ?? '';
$payload   = file_get_contents('php://input');
$expected  = 'sha256=' . hash_hmac('sha256', $payload, $secret);

if (!hash_equals($expected, $signature)) {
    http_response_code(403);
    file_put_contents($logFile, date('Y-m-d H:i:s') . " REJECTED: invalid signature\n", FILE_APPEND);
    die('Invalid signature');
}

// Only deploy pushes to main
$data   = json_decode($payload, true);
$branch = $data['ref'] ?? '';

if ($branch !== 'refs/heads/main') {
    file_put_contents($logFile, date('Y-m-d H:i:s') . " SKIPPED: push to $branch\n", FILE_APPEND);
    die('Not main branch');
}

// Deploy
$output = [];
$code   = 0;
exec("cd $repoPath && sudo -u www-data git pull origin main 2>&1", $output, $code);

$result = implode("\n", $output);
$status = $code === 0 ? 'SUCCESS' : 'FAILED';
file_put_contents($logFile, date('Y-m-d H:i:s') . " $status: $result\n", FILE_APPEND);

http_response_code($code === 0 ? 200 : 500);
echo $status;
?>
